# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: localhost:5000/node-dev:latest
before_script:
  - echo 'registry=http://server.fluxgate.de:4873/' >> ~/.npmrc
  - echo '//server.fluxgate.de:4873/:_authToken="PeTF/FIpWZ/96ffjQ/5lbBVfa8zj0HREo4YIU26Sgx0="' >> ~/.npmrc

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - name: localhost:5000/libraries_mysql
    alias: libraries_mysql

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

buildJob:
  stage: build
  script: bash bin/rebuild.sh -o
  variables:
    NODE_ENV: "ci"
    CI_DEBUG_TRACE: "true"

testJob:
  stage: test
  script: gulp tslint

deployJob:
  stage: deploy
  script: echo "should deploy"