# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:4.4.2
before_script:
  - npm install

test:lint:
  script:
    - node node_modules/gulp/bin/gulp tslint