    # 1. Update config values (localhost --> mongo and localhost --> redis) in config.development.json
    # 2. Set APP_ENV environment variable to proper value in Dockerfile-redis (default is "development")
    #    export APP_ENV=development
    # 3. Run docker-compose build
    # 4. Run docker-compose up
    # 5. Live long and prosper

version: "2"

services:
    development:
      container_name: development-libraries
      build:
        context: .
        dockerfile: .docker/docker-development.dockerfile
      hostname: "libraries-development"
      volumes:
        - .:/home/node/libraries
      working_dir: /home/node/
      env_file:
        - ./.docker/env/app.development.env
      networks:
        - libraries-network


networks:
    libraries-network:
      driver: bridge